# Generated by Django 3.1.2 on 2020-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazonAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('product_link', models.CharField(max_length=200)),
            ],
        ),
    ]
